// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efmgsripmqrpaxngdprg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmbWdzcmlwbXFycGF4bmdkcHJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjcwMjksImV4cCI6MjA3NDA0MzAyOX0.FniqonRYp9Sdvd9XkHlT36Sm5j_hR_I-MrBUT226n8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});